### PR TITLE
metapruner bugfix

### PR DESCRIPTION
**Pull request by Serjio42**
Bug fix according the Issue #130 + minor fixes.

### CODE REVIEW

**Comment by VainF** [comment]
Thank you!

**Comment by VainF** [comment]
Hello @Serjio42, the pypi package was updated to v1.1.1. Thank you once again for your assistance!

**Comment by Serjio42** [comment]
Nice to improve the library together!
I am just interested why these updates are not isible on the [library main page](https://github.com/VainF/Torch-Pruning)? Here what I see right now:
image

**Comment by VainF** [comment]
> Nice to improve the library together! I am just interested why these updates are not visible on the [library main page](https://github.com/VainF/Torch-Pruning)? Here what I see right now: image

I can't see the latest release too.

**Comment by Serjio42** [comment]
Oh, maybe it's just a matter of hand work, as I see here: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
I'm not sure because I've never managed, published any project by myself.

**Comment by VainF** [comment]
> Oh, maybe it's just a matter of hand work, as I see here: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository I'm not sure because I've never managed, published any project by myself.

Well, I just forget to set v1.1.1 as the latest version.
image

**Pull request merged**
